# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Komi-Permyak spellchecker"
koi = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Komi-Permyak, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
koi = "TRANSLATE: A spellchecker for Komi-Permyak, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.koi"

[windows]
system_product_code = "{6594974C-87EA-4BCA-97F2-5C72418F720A}_is1"
legacy_product_codes = [
    { value = "13770337-3C66-4383-8E0A-AF1F40E9C84F", kind = "nsis" },
    { value = "184C3A8C-4E53-4D12-8BE4-0CC548EC56A1", kind = "nsis" }
]

[package.speller]
name = "Komi-Permyak"
version = "0.1.1"

[package.grammar]
name = "Komi-Permyak"
version = "0.1.0"

[package.tts-text-proc]
name = "Komi-Permyak"
version = "0.1.0"
