template = "https://github.com/giellalt/template-lang-und"
rev_id = 121
template_sha = "a8e6b42c76168faa037bea034ef3c1234f58cb9d"

[replacements]
__REPO__ = "lang-koi"
__UND2C__ = "koi"
__UNDEFINED__ = "Komi-Permyak"
__UND__ = "koi"
