template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "komi1269"
__REPO__ = "lang-koi"
__UND2C__ = "koi"
__UNDEFINED__ = "Komi-Permyak"
__UND__ = "koi"
